### ISSUE TITLE
TestCaseFilter appears to be ignored.

### ISSUE THREAD

**Issue by jonathh21** [machine-visualstudio/machine.vstestadapter#58] opened 2016-04-01 09:33 UTC
Any filters that are passed in seem to being ignored, 

Example: 
/TestCaseFilter:"Priority=1"
Example: /TestCaseFilter:"TestCategory=Nightly|FullyQualifiedName=Namespace.ClassName.MethodName"

Is anyone else experiencing this?

This may be related to [https://github.com/machine-visualstudio/machine.vstestadapter/issues/15](url) it may not..

**Comment by ivanz** [comment] 2016-04-01 16:16
Closing this as duplicate of #15

**Closed by ivanz** 2016-04-01 16:16 UTC
